name: Merge To Earn

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Hello world
        options:
          - monalisa
          - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
  merge_to_earn:
    name: Merge to earn
    # if: github.repository == 'github/docs-internal'
    runs-on: ubuntu-latest
    # env:
    #   GITHUB_TOKEN: ${{ secrets.DOCUBOT_READORG_REPO_WORKFLOW_SCOPES }}
    #   FIRST_RESPONDER_PROJECT: Docs content first responder
    #   REPORT_AUTHOR: docubot
    #   REPORT_LABEL: broken link report
    #   REPORT_REPOSITORY: github/docs-content
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: npm ci
        run: npm ci
      - name: Run script
        run: |
          script/mergeToEarn.js
