name: Merge To Earn

on:
  workflow_dispatch:
    inputs:
      address:
        required: true
        description: Address or ENS
      slices:
        type: integer
        required: true

jobs:
  mint_slices_job:
    runs-on: ubuntu-latest
    name: Merge to Earn | Mint slices
    steps:
      - name: Mint slices
        id: mint
        uses: Dom-Mac/merge-to-earn@v3.2.5
        with:
          slicer: "0x775e6c6a298b704f95500e752cf5b649fb3bdd73"
          alchemy_api_key: ${{ secrets.ALCHEMY_API_KEY }}
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.mint.outputs.time }}"
