name: Merge To Earn

on:
  issue_comment:
    type: [created]
  push:
    branches:
      - "main"

jobs:
  mint_slices_job:
    name: Merge to Earn | Mint slices
    if: ${{ github.event.issue.pull_request || github.event.push.push_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Mint slices
        id: mint
        uses: Dom-Mac/merge-to-earn@v3.2.9
        with:
          slicer: "0x775e6c6a298b704f95500e752cf5b649fb3bdd73"
          alchemy_api_key: ${{ secrets.ALCHEMY_API_KEY }}
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.mint.outputs.time }}"
